---
- name: add container backend
  apt:
    update_cache: yes
    name: docker.io
- name: present daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
- name: enable docker
  service:
    name: docker
    state: started
    enabled: yes